version: "3.7"

services:
  ros:
    build: .
    image: my-ros-gui
    container_name: my-ros-test
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/home/max/projects:/home/projects"
    working_dir: /home/projects
    environment:
      - DISPLAY
    network_mode: host
