version: "3.7"

services:
  ros:
    build: .
    image: ros_gui
    container_name: ros_test
    volumes: ["/tmp/.X11-unix:/tmp/.X11-unix:rw"]
    environment:
      - DISPLAY
    network_mode: host
